/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Proceso;
import datastructura.ListaEnlazada;
import java.util.concurrent.Semaphore;
import logic.CPUThread;



/**
 *
 * @author Gloria
 */
public class VentanaPrincipal extends javax.swing.JFrame {
// Esta es la cola donde guardo los procesos generados
datastructura.ListaEnlazada colaListos = new datastructura.ListaEnlazada();
datastructura.ListaEnlazada colaBloqueados = new datastructura.ListaEnlazada();
datastructura.ListaEnlazada colaSuspendidos = new datastructura.ListaEnlazada();

int segundosMision = 0;
private int contadorGlobal = 1; // Para que P1, P2... funcionen
private Semaphore semaforoGlobal = new Semaphore(1);
private CPUThread cpu;
// Para llevar el control de los 200MB de RAM
clases.Proceso procesoEnEjecucion = null;
    /**
     * Creates new form VentanaPrincipal
     */
// El satélite tiene una RAM limitada
private final int MAX_MEMORIA_RAM = 200; // MB
private int memoriaUsadaActual = 0;

public int getSegundosMision(){
    return segundosMision;
}


    public VentanaPrincipal() {
        initComponents();
       
        cpu = new CPUThread(colaListos, colaBloqueados, semaforoGlobal, this);
        cpu.start(); 
        
        new javax.swing.Timer(1000, (e) ->{
            segundosMision++;
            actualizarTabla();
            
            lblReloj.setText("Reloj de mision: "+ segundosMision + "s");
        }).start();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblReloj = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProcesos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSwap = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnInterrupcion = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReloj.setText("Reloj de Misión: 00:00");

        tblProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Instrucciones", "Prioridad", "Deadline", "PC", "MAR", "Memoria(MB)", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProcesos);

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane3.setViewportView(txtLog);

        tblSwap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Memoria", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblSwap);

        jLabel1.setText("Procesos en Disco");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblReloj))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblReloj)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnInterrupcion.setText("SIMULAR IMPACTO");
        btnInterrupcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterrupcionActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar 20 Procesos");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(btnInterrupcion)
                .addGap(88, 88, 88)
                .addComponent(btnGenerar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInterrupcion)
                    .addComponent(btnGenerar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
      
        try{
            semaforoGlobal.acquire();
        
                for (int i = 1; i <= 20; i++) {
                String id = "P" + contadorGlobal;
                String nombre = "Tarea_" + contadorGlobal;
                int instrucciones = (int) (Math.random() * 50) + 10;
                int prioridad = (int) (Math.random() * 5) + 1; // Prioridad del 1 al 5
                int memoriaMB = (int) (Math.random() * 50) + 10; // Memoria aleatoria
                int deadline = (int) (Math.random() * 100) + 50;
                
                clases.Proceso nuevo = new clases.Proceso(id, nombre, instrucciones, prioridad, deadline);
                nuevo.setEstado("Nuevo");
                // cabe en ram
                if (memoriaUsadaActual + memoriaMB <= 200) { 
                    nuevo.setEstado("Listo");
                    colaListos.agregar(nuevo); 
                    memoriaUsadaActual += memoriaMB;
                    escribirLog("ADMITIDO: " + nombre + " en RAM (" + memoriaMB + "MB)");
                } else {
                    // Si no cabe, se va a la cola de Suspendidos
                    nuevo.setEstado("Suspendido");
                    colaSuspendidos.agregar(nuevo);
                    escribirLog("SWAP: " + nombre + " enviado a disco por falta de RAM");
                }
                contadorGlobal++;
            }
            ordenarColaPorPrioridad(colaListos); 
            semaforoGlobal.release();
            actualizarTabla();
        }catch (InterruptedException e) {}
    }//GEN-LAST:event_btnGenerarActionPerformed

    
    
    private void ordenarColaPorPrioridad(datastructura.ListaEnlazada lista) {
    if (lista.estaVacia()) return;
    
    boolean intercambio;
    do {
        intercambio = false;
        datastructura.Nodo actual = lista.getInicio();
        while (actual != null && actual.getSiguiente() != null) {
            if (actual.getDato().getPrioridad() > actual.getSiguiente().getDato().getPrioridad()) {
                clases.Proceso temp = actual.getDato();
                actual.setDato(actual.getSiguiente().getDato());
                actual.getSiguiente().setDato(temp);
                intercambio = true;
            }
            actual = actual.getSiguiente();
        }
    } while (intercambio);
}
    private void btnInterrupcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterrupcionActionPerformed
       cpu.activarInterrupcion();
       escribirLog("iMPACTO DETECTADO: Enviando al satelite");
    }//GEN-LAST:event_btnInterrupcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnInterrupcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JTable tblProcesos;
    private javax.swing.JTable tblSwap;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables

    public void actualizarTabla() {
    // 1. Acceso manual
    javax.swing.table.DefaultTableModel modeloRAM = (javax.swing.table.DefaultTableModel) tblProcesos.getModel();
    javax.swing.table.DefaultTableModel modeloSwap = (javax.swing.table.DefaultTableModel) tblSwap.getModel();

    // Limpio filas sin crear objetos nuevos
    modeloRAM.setRowCount(0);
    modeloSwap.setRowCount(0);

    
    clases.Proceso ejec = cpu.getProcesoEnEjecucion();
    if (ejec != null) {
        Object[] filaEjec = {
            ejec.getId(), ejec.getNombre(), ejec.getInstruccionesTotales(),
            ejec.getPrioridad(), ejec.getTiempoLimite(), ejec.getPc(),
            ejec.getMar(), ejec.getMemoriaMb(), "Ejecucion"
        };
        modeloRAM.addRow(filaEjec);
    }

    // -(Cola de Listos)
    datastructura.Nodo auxListos = colaListos.getInicio();
    while (auxListos != null) {
        clases.Proceso p = auxListos.getDato();
        Object[] filaListo = {
            p.getId(), p.getNombre(), p.getInstruccionesTotales(),
            p.getPrioridad(), p.getTiempoLimite(), p.getPc(),
            p.getMar(), p.getMemoriaMb(), p.getEstado()
        };
        modeloRAM.addRow(filaListo);
        auxListos = auxListos.getSiguiente();
    }

    //  LLEno SWAP (Cola de Suspendidos) 
    datastructura.Nodo auxSwap = colaSuspendidos.getInicio();
    while (auxSwap != null) {
        clases.Proceso p = auxSwap.getDato();
        Object[] filaSwap = {
            p.getId(), p.getNombre(), p.getMemoriaMb(), "Suspendido"
        };
        modeloSwap.addRow(filaSwap);
        auxSwap = auxSwap.getSiguiente();
    }
}
    
    public void escribirLog(String mensaje) {
   txtLog.append("[" + segundosMision + "s] " + mensaje + "\n");
     txtLog.setCaretPosition( txtLog.getDocument().getLength());
}
    public void liberarMemoriaYRevisarSuspendidos(int memoriaLiberada) {
    memoriaUsadaActual -= memoriaLiberada;
    escribirLog("RAM: Se liberaron " + memoriaLiberada + "MB. actual: " + memoriaUsadaActual + "/200MB");

    if (!colaSuspendidos.estaVacia()) {
        clases.Proceso pS = colaSuspendidos.getInicio().getDato();
        
        if (memoriaUsadaActual + pS.getMemoriaMb() <= MAX_MEMORIA_RAM) {
            colaSuspendidos.eliminarPrimero();
            pS.setEstado("Listo");
            colaListos.agregar(pS);
            memoriaUsadaActual += pS.getMemoriaMb();
            escribirLog("SWAP: " + pS.getNombre() + " movido a RAM.");
            
            ordenarColaPorPrioridad(colaListos);
        }
    }
    actualizarTabla(); // Para que se vea el cambio inmediatamente
  }
}


