/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Proceso;
import datastructura.ListaEnlazada;

/**
 *
 * @author Gloria
 */
public class VentanaPrincipal extends javax.swing.JFrame {
// Esta es la cola donde guardo los procesos generados
datastructura.ListaEnlazada colaListos = new datastructura.ListaEnlazada();
int segundosMision = 0;
clases.Proceso procesoEnEjecucion = null;
    /**
     * Creates new form VentanaPrincipal
     */
// El satélite tiene una RAM limitada
private final int MAX_MEMORIA_RAM = 200; // MB
private int memoriaUsadaActual = 0;


    public VentanaPrincipal() {
        initComponents();
        
            Thread hiloPrincipal = new Thread() {
                @Override
                public void run() {
                    while (true) {
                        try {
                            Thread.sleep(1000); // 1 segundo
                            segundosMision++;
                            lblReloj.setText("Reloj de Misión: " + segundosMision + "s");

                            // Lógica del satélite
                            ejecutarProcesador();

                        } catch (Exception e) { }
                    }
                }
            };
            hiloPrincipal.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblReloj = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReloj.setText("Reloj de Misión: 00:00");

        btnGenerar.setText("Generar 20 Procesos");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Instrucciones", "Prioridad", "Deadline", "PC", "MAR", "Memoria(MB)", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane3.setViewportView(txtLog);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(358, 358, 358))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblReloj)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblReloj)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(btnGenerar)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 220, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
      for (int i = 1; i <= 20; i++) {
        int instrucciones = (int) (Math.random() * 50) + 10;
        int prioridad = (int) (Math.random() * 5) + 1;
        int deadline = (int) (Math.random() * 100) + 20;

        clases.Proceso nuevo = new clases.Proceso("P" + i, "Tarea_" + i, instrucciones, prioridad, deadline);
        
        // Lógica de Admisión por Memoria
        if (memoriaUsadaActual + nuevo.getMemoriaMb() <= MAX_MEMORIA_RAM) {
            nuevo.setEstado("Listo");
            colaListos.agregar(nuevo);
            memoriaUsadaActual += nuevo.getMemoriaMb();
            escribirLog("ADMITIDO: " + nuevo.getNombre() + " en RAM (" + nuevo.getMemoriaMb() + "MB)");
        } else {
            // colaSuspendidos (ListaEnlazada)
            nuevo.setEstado("Listo/Suspendido");
            escribirLog("SWAP: " + nuevo.getNombre() + " enviado a disco por falta de RAM.");
            // colaSuspendidos.agregar(nuevo); 
        }
    }
    actualizarTabla();
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables

    public void actualizarTabla() {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);
    
    datastructura.Nodo aux = colaListos.getInicio(); 
    while (aux != null) {
        clases.Proceso p = aux.getDato();
        //  los datos en el orden de las columnas de diseño
        modelo.addRow(new Object[]{
            p.getId(), 
            p.getNombre(), 
            p.getInstruccionesTotales(), 
            p.getPrioridad(), 
            p.getTiempoLimite(),
            p.getPc(),     
            p.getMar(),    
            p.getEstado()   
        });
        aux = aux.getSiguiente();
    }

    // que proceso se esta ejecutando
    if (procesoEnEjecucion != null) {
        modelo.addRow(new Object[]{
            procesoEnEjecucion.getId(), 
            procesoEnEjecucion.getNombre(), 
            procesoEnEjecucion.getInstruccionesTotales(), 
            procesoEnEjecucion.getPrioridad(), 
            procesoEnEjecucion.getTiempoLimite(),
            procesoEnEjecucion.getPc(),
            procesoEnEjecucion.getMar(),
            procesoEnEjecucion.getMemoriaMb(),
            procesoEnEjecucion.getEstado()
        });
    }
}

    public void ejecutarProcesador() {
    if (procesoEnEjecucion == null) {
        procesoEnEjecucion = colaListos.eliminarPrimero();
        if (procesoEnEjecucion != null) {
            procesoEnEjecucion.setEstado("Ejecución");
            actualizarTabla();
            escribirLog("Satélite inició: " + procesoEnEjecucion.getNombre() + " [Prioridad " + procesoEnEjecucion.getPrioridad() + "]");
        }
    } else {
        //  Verifico Deadline 
        if (segundosMision > procesoEnEjecucion.getTiempoLimite()) {
            escribirLog("¡FALLO CRÍTICO! Deadline superado en: " + procesoEnEjecucion.getNombre());
            procesoEnEjecucion.setEstado("FALLIDO");
            procesoEnEjecucion = null;
            actualizarTabla();
            return;
        }

       
        procesoEnEjecucion.ejecutarCiclo();
        
       
        if (procesoEnEjecucion.getInstruccionesTotales() <= 0) {
            escribirLog("ÉXITO: " + procesoEnEjecucion.getNombre() + " completó su misión.");
            procesoEnEjecucion.setEstado("Terminado");
            procesoEnEjecucion = null;
        }
        
        actualizarTabla();
    }
}
    
    public void escribirLog(String mensaje) {
   txtLog.append("[" + segundosMision + "s] " + mensaje + "\n");
     txtLog.setCaretPosition( txtLog.getDocument().getLength());
}
}


